In [1]:
import numpy as np

## 1. vector-vector multiplication

In [2]:
u = np.array([2, 4, 5, 6])

In [3]:
v = np.array([1, 0, 0, 2])

In [8]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0

    for i in range(n):
        print('u: ', u[i], '*', 'v: ', v[i], '=', u[i] * v[i])
        result = result + u[i] * v[i]
        print('result: ', result)

    return result

In [9]:
vector_vector_multiplication(u, v)

u:  2 * v:  1 = 2
result:  2.0
u:  4 * v:  0 = 0
result:  2.0
u:  5 * v:  0 = 0
result:  2.0
u:  6 * v:  2 = 12
result:  14.0


14.0

In [12]:
u.dot(v)

14

## 2. matrix-vector multiplication

In [17]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

v = np.array([1, 0, 0, 2])

def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
        print('vector_result: ', result[i])

    return result

matrix_vector_multiplication(U, v)

u:  2 * v:  1 = 2
result:  2.0
u:  4 * v:  0 = 0
result:  2.0
u:  5 * v:  0 = 0
result:  2.0
u:  6 * v:  2 = 12
result:  14.0
vector_result:  14.0
u:  1 * v:  1 = 1
result:  1.0
u:  2 * v:  0 = 0
result:  1.0
u:  1 * v:  0 = 0
result:  1.0
u:  2 * v:  2 = 4
result:  5.0
vector_result:  5.0
u:  3 * v:  1 = 3
result:  3.0
u:  1 * v:  0 = 0
result:  3.0
u:  2 * v:  0 = 0
result:  3.0
u:  1 * v:  2 = 2
result:  5.0
vector_result:  5.0


array([14.,  5.,  5.])

In [18]:
U.dot(v)

array([14,  5,  5])

## 3. matrix-matrix multiplication

In [19]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0],
])

def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

matrix_matrix_multiplication(U, V)


U.dot(V)

u:  2 * v:  1.0 = 2.0
result:  2.0
u:  4 * v:  0.0 = 0.0
result:  2.0
u:  5 * v:  0.0 = 0.0
result:  2.0
u:  6 * v:  2.0 = 12.0
result:  14.0
vector_result:  14.0
u:  1 * v:  1.0 = 1.0
result:  1.0
u:  2 * v:  0.0 = 0.0
result:  1.0
u:  1 * v:  0.0 = 0.0
result:  1.0
u:  2 * v:  2.0 = 4.0
result:  5.0
vector_result:  5.0
u:  3 * v:  1.0 = 3.0
result:  3.0
u:  1 * v:  0.0 = 0.0
result:  3.0
u:  2 * v:  0.0 = 0.0
result:  3.0
u:  1 * v:  2.0 = 2.0
result:  5.0
vector_result:  5.0
u:  2 * v:  1.0 = 2.0
result:  2.0
u:  4 * v:  0.5 = 2.0
result:  4.0
u:  5 * v:  2.0 = 10.0
result:  14.0
u:  6 * v:  1.0 = 6.0
result:  20.0
vector_result:  20.0
u:  1 * v:  1.0 = 1.0
result:  1.0
u:  2 * v:  0.5 = 1.0
result:  2.0
u:  1 * v:  2.0 = 2.0
result:  4.0
u:  2 * v:  1.0 = 2.0
result:  6.0
vector_result:  6.0
u:  3 * v:  1.0 = 3.0
result:  3.0
u:  1 * v:  0.5 = 0.5
result:  3.5
u:  2 * v:  2.0 = 4.0
result:  7.5
u:  1 * v:  1.0 = 1.0
result:  8.5
vector_result:  8.5
u:  2 * v:  2.0 = 4.0
result:  4.

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## 4. Identity matrix and Inverse Matrices

In [20]:
# Identity matrix
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0],
])

V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [24]:
# Inverse matrix
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [25]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [26]:
# return identity matrix
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])