In [2]:
import pandas as pd
import numpy as np

In [3]:
# Question 1 What's the version of Pandas that you installed?
pd.__version__

'2.0.3'

In [8]:
# How many columns are in the dataset?
# housing = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv')

In [9]:
housing_df = pd.read_csv('data/housing.csv')

In [10]:
housing_df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [11]:
housing_df.shape

(20640, 10)

In [24]:
# Question 3 Which columns in the dataset have missing values?
housing_df.isnull().sum()[housing_df.isnull().sum() > 0].index

Index(['total_bedrooms'], dtype='object')

In [25]:
# Question 4 How many unique values does the ocean_proximity column have?
housing_df['ocean_proximity'].nunique()

5

In [26]:
housing_df['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [27]:
# Question 5 What's the average value of the median_house_value for the houses located near the bay?
housing_df[housing_df['ocean_proximity'] == 'NEAR BAY']['median_house_value'].mean()

259212.31179039303

In [28]:
housing_df.groupby('ocean_proximity')['median_house_value'].mean()

ocean_proximity
<1H OCEAN     240084.285464
INLAND        124805.392001
ISLAND        380440.000000
NEAR BAY      259212.311790
NEAR OCEAN    249433.977427
Name: median_house_value, dtype: float64

In [34]:
housing_df[['median_house_value', 'ocean_proximity']].groupby('ocean_proximity').mean()

median_house_value
ocean_proximity                    
<1H OCEAN             240084.285464
INLAND                124805.392001
ISLAND                380440.000000
NEAR BAY              259212.311790
NEAR OCEAN            249433.977427

In [39]:
# Question 6
# Calculate the average of total_bedrooms column in the dataset.
# Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
# Now, calculate the average of total_bedrooms again.

bed_mean = round(housing_df['total_bedrooms'].mean(), 2)
housing_df['total_bedrooms'].fillna(bed_mean, inplace=True)
fill_mean = round(housing_df['total_bedrooms'].mean(), 2)
print(f'Before fillna: {bed_mean}')
print(f'After fillna: {fill_mean}')

Before fillna: 537.87
After fillna: 537.87


In [46]:
# Question 7 Select all the options located on islands
housing_df[housing_df['ocean_proximity'] == 'ISLAND']

# Select only columns housing_median_age, total_rooms, total_bedrooms. Get the underlying NumPy array. Let's call it X.
X = housing_df[housing_df['ocean_proximity'] == 'ISLAND'][['housing_median_age', 'total_rooms', 'total_bedrooms']].values

In [47]:
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [73]:
X.T

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [76]:
X.T.dot(X)

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [77]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = X.T.dot(X)

In [78]:
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [79]:
# Compute the inverse of XTX.
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [80]:
y = np.array([950, 1300, 800, 1000, 1300])

In [83]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = XTX_inv.dot(X.T)#.dot(y)

In [84]:
w

array([[-0.00825608, -0.00653208, -0.00232159,  0.02565144,  0.01204934],
       [-0.00165852,  0.0011141 ,  0.00139656, -0.00103215, -0.00110698],
       [ 0.00754365, -0.00301964, -0.00455125,  0.00181685,  0.00329418]])

In [85]:
w.dot(y)

array([23.12330961, -1.48124183,  5.69922946])